import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "@/app/_styles/globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ReservationProvider } from "./context/ReservationContext";
import { Toaster } from "react-hot-toast";

const josefin = Josefin_Sans({
  subsets: ["latin", "vietnamese"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | The Wild Oasis",
    default: "Welcome The Wild Oasis",
  },
  description: "Generated by The Wild Oasis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} flex flex-col mx-auto antialiased justify-between bg-primary-950 text-primary-100 min-h-screen max-w-7xl py-2 px-4 md:py-4 md:px-8`}
      >
        <Header />
        <div className="flex-1 md:px-8 md:py-12 px-4 py-6 grid w-full">
          <main>
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
        <Toaster position="bottom-right" />
        <Footer />
      </body>
    </html>
  );
}
